arb-dir: lib/l10n #? this the directory of the translate file
template-arb-file: app_en.arb #? this to the english file this is a defult 
output-localization-file: app_localizations.dart #? this to the localization file