// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ6uuIBDhHRu2BtDl6rYoDxTGBDn14hVk',
    appId: '1:1024353086757:web:249302e27dd81c9b55becc',
    messagingSenderId: '1024353086757',
    projectId: 'evently-f0c1b',
    authDomain: 'evently-f0c1b.firebaseapp.com',
    storageBucket: 'evently-f0c1b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClBka7z8pyHWINoekb2yFzS_LCngii0N0',
    appId: '1:1024353086757:android:698a0932da75abc055becc',
    messagingSenderId: '1024353086757',
    projectId: 'evently-f0c1b',
    storageBucket: 'evently-f0c1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGUn9t4XELdUtiqYwvua9WUqzgEhHURRo',
    appId: '1:1024353086757:ios:78713ae052cb429355becc',
    messagingSenderId: '1024353086757',
    projectId: 'evently-f0c1b',
    storageBucket: 'evently-f0c1b.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGUn9t4XELdUtiqYwvua9WUqzgEhHURRo',
    appId: '1:1024353086757:ios:78713ae052cb429355becc',
    messagingSenderId: '1024353086757',
    projectId: 'evently-f0c1b',
    storageBucket: 'evently-f0c1b.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ6uuIBDhHRu2BtDl6rYoDxTGBDn14hVk',
    appId: '1:1024353086757:web:681ec674f8ddb88d55becc',
    messagingSenderId: '1024353086757',
    projectId: 'evently-f0c1b',
    authDomain: 'evently-f0c1b.firebaseapp.com',
    storageBucket: 'evently-f0c1b.firebasestorage.app',
  );

}